apiVersion: v1
kind: Service
metadata:
  name: {{ include "cloud-carbon-footprint.fullname" . }}-client
  labels:
    {{- include "cloud-carbon-footprint.labels" . | nindent 4 }}
    app.kubernetes.io/component: client
spec:
  type: {{ .Values.client.service.type }}
  ports:
    - port: {{ .Values.client.service.port.number }}
      targetPort: {{ .Values.client.service.port.name }}
      protocol: {{ .Values.client.service.port.protocol }}
      name: {{ .Values.client.service.port.name }}
  selector:
    {{- include "cloud-carbon-footprint.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: client
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cloud-carbon-footprint.fullname" . }}-api
  labels:
    {{- include "cloud-carbon-footprint.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - port: {{ .Values.api.service.port.number }}
      targetPort: {{ .Values.api.service.port.name }}
      protocol: {{ .Values.api.service.port.protocol }}
      name: {{ .Values.api.service.port.name }}
  selector:
    {{- include "cloud-carbon-footprint.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
